/** @type {import('tailwindcss').Config} */
export default {
  content: [
    './index.html',
    './src/**/*.{ts,tsx}',
    './.storybook/**/*.{ts,tsx}',
  ],
  theme: {
    extend: {
      colors: {
        bg: 'var(--bg)',
        'bg-2': 'var(--bg-2)',
        'bg-3': 'var(--bg-3)',
        'text-default': 'var(--text)',
        'text-2': 'var(--text-2)',
        border: 'var(--border)',
        'heading-accent': 'var(--heading-accent)',
        'btn-bg': 'var(--btn-bg)',
        'btn-text': 'var(--btn-text)',
        'btn-bg-hover': 'var(--btn-bg-hover)',
        'btn2-bg': 'var(--btn2-bg)',
        'btn2-text': 'var(--btn2-text)',
        'btn2-border': 'var(--btn2-border)',
        'btn2-bg-hover': 'var(--btn2-bg-hover)',
        'btn2-text-hover': 'var(--btn2-text-hover)',
        'accent-btn': 'var(--accent-btn-bg)',
        'accent-btn-text': 'var(--accent-btn-text)',
        'accent-highlight': 'var(--accent-accent-highlight)',
        'pink-500': 'var(--pink-500)',
        'pink-accent': 'var(--pink-accent)',
        'pink-600': 'var(--pink-600)',
        'yellow-500': 'var(--yellow-500)',
        'yellow-600': 'var(--yellow-600)',
        'dark-800': 'var(--dark-800)',
        'dark-900': 'var(--dark-900)',
        'brand-text': 'var(--brand-text)',
        'light-100': 'var(--light-100)',
        'light-200': 'var(--light-200)',
        'purple-navy': 'var(--purple-navy)',
        'purple-500': 'var(--purple-500)',
        'purple-700': 'var(--purple-700)',
        'purple-800': 'var(--purple-800)',
        'pink-vivid': 'var(--pink-vivid)',
        'pink-vivid-light': 'var(--pink-vivid-light)',
        'pink-mist': 'var(--pink-mist)',
        'fuschia-highlight': 'var(--fuschia-highlight)',
        'fuschia-text': 'var(--fuschia-text)',
        'yellow-highlight': 'var(--yellow-highlight)',
        'yellow-hover': 'var(--yellow-hover)',
        'brand-hover': 'var(--brand-hover)',
      },
      borderRadius: {
        section: 'var(--radius-section)',
        card: 'var(--radius-card)',
        sm: 'var(--radius-small)',
        pill: 'var(--radius-pill)',
        dropdown: 'var(--radius-dropdown)',
      },
      fontSize: {
        display: ['var(--font-size-display)', { lineHeight: '1', letterSpacing: '-0.05em' }],
        h1: ['var(--font-size-h1)', { lineHeight: '1', letterSpacing: '-0.05em' }],
        h2: ['var(--font-size-h2)', { lineHeight: '1', letterSpacing: '-0.05em' }],
        h3: ['var(--font-size-h3)', { lineHeight: '1.3', letterSpacing: '-0.05em' }],
        h4: ['var(--font-size-h4)', { lineHeight: '1.3', letterSpacing: '-0.05em' }],
        h5: ['var(--font-size-h5)', { lineHeight: '1.3' }],
        h6: ['var(--font-size-h6)', { lineHeight: '1.3' }],
        'text-large': ['var(--font-size-text-large)', { lineHeight: '1.5' }],
        'text-main': ['var(--font-size-text-main)', { lineHeight: '1.5' }],
        'text-small': ['var(--font-size-text-small)', { lineHeight: '1.5' }],
        'text-xsmall': ['var(--font-size-text-xsmall)', { lineHeight: '1.5' }],
      },
      spacing: {
        'section-y': 'var(--spacing-section-y)',
      },
    },
  },
  plugins: [],
}
