/** @type {import('tailwindcss').Config} */
export default {
  content: [
    './index.html',
    './src/**/*.{ts,tsx}',
    './.storybook/**/*.{ts,tsx}',
  ],
  theme: {
    extend: {
      colors: {
        bg: 'var(--bg)',
        'bg-2': 'var(--bg-2)',
        'bg-3': 'var(--bg-3)',
        'text-default': 'var(--text)',
        'text-2': 'var(--text-2)',
        border: 'var(--border)',
        'heading-accent': 'var(--heading-accent)',
        'btn-bg': 'var(--btn-bg)',
        'btn-text': 'var(--btn-text)',
        'btn-bg-hover': 'var(--btn-bg-hover)',
        'btn2-bg': 'var(--btn2-bg)',
        'btn2-text': 'var(--btn2-text)',
        'btn2-border': 'var(--btn2-border)',
        'btn2-bg-hover': 'var(--btn2-bg-hover)',
        'btn2-text-hover': 'var(--btn2-text-hover)',
        'accent-btn': 'var(--accent-btn-bg)',
        'accent-btn-text': 'var(--accent-btn-text)',
        'accent-highlight': 'var(--accent-accent-highlight)',
        'black': 'var(--black)',
        'transparent': 'var(--transparent)',
        'pink-500': 'var(--pink-500)',
        'pink-accent': 'var(--pink-accent)',
        'pink-600': 'var(--pink-600)',
        'yellow-500': 'var(--yellow-500)',
        'yellow-600': 'var(--yellow-600)',
        'dark-800': 'var(--dark-800)',
        'dark-900': 'var(--dark-900)',
        'brand-text': 'var(--brand-text)',
        'light-100': 'var(--light-100)',
        'light-200': 'var(--light-200)',
        'purple-navy': 'var(--purple-navy)',
        'purple-500': 'var(--purple-500)',
        'purple-700': 'var(--purple-700)',
        'pink-vivid': 'var(--pink-vivid)',
        'pink-vivid-light': 'var(--pink-vivid-light)',
        'pink-mist': 'var(--pink-mist)',
        'fuschia-highlight': 'var(--fuschia-highlight)',
        'fuschia-700': 'var(--fuschia-700)',
        'fuschia-hover': 'var(--fuschia-hover)',
        'fuschia-text': 'var(--fuschia-text)',
        'purple-600': 'var(--purple-600)',
        'purple-hover': 'var(--purple-hover)',
        'blue-highlight': 'var(--blue-highlight)',
        'blue-btn-bg': 'var(--blue-btn-bg)',
        'blue-btn-hover': 'var(--blue-btn-hover)',
        'blue-navy': 'var(--blue-navy)',
        'yellow-highlight': 'var(--yellow-highlight)',
        'yellow-hover': 'var(--yellow-hover)',
        'brand-hover': 'var(--brand-hover)',
        'teal-100': 'var(--teal-100)',
        'teal-700': 'var(--teal-700)',
      },
      borderRadius: {
        section: 'var(--radius-section)',
        card: 'var(--radius-card)',
        sm: 'var(--radius-small)',
        pill: 'var(--radius-pill)',
        dropdown: 'var(--radius-dropdown)',
      },
      fontSize: {
        'display': ['var(--font-size-display)', { lineHeight: 'var(--line-height-display)', letterSpacing: 'var(--letter-spacing-display)' }],
        'display-xl': ['var(--font-size-display-xl)', { lineHeight: 'var(--line-height-display-xl)', letterSpacing: 'var(--letter-spacing-display-xl)' }],
        'h1': ['var(--font-size-h1)', { lineHeight: 'var(--line-height-h1)', letterSpacing: 'var(--letter-spacing-h1)' }],
        'h2': ['var(--font-size-h2)', { lineHeight: 'var(--line-height-h2)', letterSpacing: 'var(--letter-spacing-h2)' }],
        'h3': ['var(--font-size-h3)', { lineHeight: 'var(--line-height-h3)', letterSpacing: 'var(--letter-spacing-h3)' }],
        'h4': ['var(--font-size-h4)', { lineHeight: 'var(--line-height-h4)', letterSpacing: 'var(--letter-spacing-h4)' }],
        'h5': ['var(--font-size-h5)', { lineHeight: 'var(--line-height-h5)', letterSpacing: 'var(--letter-spacing-h5)' }],
        'h6': ['var(--font-size-h6)', { lineHeight: 'var(--line-height-h6)', letterSpacing: 'var(--letter-spacing-h6)' }],
        'text-large': ['var(--font-size-text-large)', { lineHeight: 'var(--line-height-text-large)', letterSpacing: 'var(--letter-spacing-text-large)' }],
        'text-main': ['var(--font-size-text-main)', { lineHeight: 'var(--line-height-text-main)', letterSpacing: 'var(--letter-spacing-text-main)' }],
        'text-small': ['var(--font-size-text-small)', { lineHeight: 'var(--line-height-text-small)', letterSpacing: 'var(--letter-spacing-text-small)' }],
        'text-xsmall': ['var(--font-size-text-xsmall)', { lineHeight: 'var(--line-height-text-xsmall)', letterSpacing: 'var(--letter-spacing-text-xsmall)' }],
        'text-large-semibold': ['var(--font-size-text-large-semibold)', { lineHeight: 'var(--line-height-text-large-semibold)', letterSpacing: 'var(--letter-spacing-text-large-semibold)' }],
        'text-main-semibold': ['var(--font-size-text-main-semibold)', { lineHeight: 'var(--line-height-text-main-semibold)', letterSpacing: 'var(--letter-spacing-text-main-semibold)' }],
        'text-small-semibold': ['var(--font-size-text-small-semibold)', { lineHeight: 'var(--line-height-text-small-semibold)', letterSpacing: 'var(--letter-spacing-text-small-semibold)' }],
        'text-xsmall-semibold': ['var(--font-size-text-xsmall-semibold)', { lineHeight: 'var(--line-height-text-xsmall-semibold)', letterSpacing: 'var(--letter-spacing-text-xsmall-semibold)' }],
        'label': ['var(--font-size-label)', { lineHeight: 'var(--line-height-label)', letterSpacing: 'var(--letter-spacing-label)' }],
      },
      fontFamily: {
        brand: ['Murfy A2', 'sans-serif'],
        sans: ['Murfy A2', 'sans-serif'],
      },
      spacing: {
        'section-y': 'var(--spacing-section-y)',
      },
    },
  },
  plugins: [],
}
