import React from 'react'
import type { Meta, StoryObj } from '@storybook/react'
import { DocHeader, DocSection } from './Foundation/doc-components'
import { Button } from './Atoms/Button/Button'

const meta: Meta = {
  title: 'Introduction',
  parameters: { layout: 'fullscreen' },
}
export default meta
type Story = StoryObj

// ─── Vertical / accent data ───────────────────────────────────────────────────

const verticals = [
  {
    name: 'Électroménager',
    emoji: '⚙️',
    accent: 'violet' as const,
    label: 'Violet',
    description: "Appliance repair — Murfy's core activity",
  },
  {
    name: 'Chauffage',
    emoji: '🔥',
    accent: 'fuschia' as const,
    label: 'Fuschia',
    description: 'Heating — new expansion vertical',
  },
  {
    name: 'Solaire',
    emoji: '☀️',
    accent: 'yellow' as const,
    label: 'Yellow',
    description: 'Solar — new expansion vertical',
  },
  {
    name: 'Brand Baseline',
    emoji: '🌸',
    accent: 'default' as const,
    label: 'Default (pink)',
    description: 'Global UI, marketing surfaces, no-vertical contexts',
  },
]

// ─── Component layer data ─────────────────────────────────────────────────────

const layers = [
  {
    name: 'Foundation',
    count: 9,
    emoji: '🎨',
    description: 'Colors, Typography, Spacing, Icons, Grid, A11y, Naming, Themes',
  },
  {
    name: 'Atoms',
    count: 6,
    emoji: '⚛️',
    description: 'Button, Input, Tag, StatItem, TrustpilotBadge, TrustpilotStars',
  },
  {
    name: 'Molecules',
    count: 8,
    emoji: '🧩',
    description: 'Card, AccordionItem, Footer, HeroSearchBar, PostalCodeForm, NewsletterForm, VerticalSelector, WhyMurfyCard',
  },
  {
    name: 'Organisms',
    count: 15,
    emoji: '🏗️',
    description: 'HeroSection, Navbar, FaqSection, TrustpilotSection, ProcessSection, + 10 more',
  },
  {
    name: 'Templates',
    count: 2,
    emoji: '📐',
    description: 'HomePage, ChauffagePage — full-page layout scaffolds',
  },
]

// ─── Token pipeline steps ─────────────────────────────────────────────────────

const pipelineSteps = [
  {
    file: 'tokens.json',
    arrow: true,
    description: 'Source of truth — primitives, theme semantic roles, and accent overrides defined here. Never edit generated files.',
  },
  {
    file: 'tokens.css',
    arrow: true,
    description: 'Auto-generated by `npm run build-tokens`. Emits CSS custom properties for :root, [data-theme="…"], and [data-accent="…"] selectors.',
  },
  {
    file: 'tailwind.config.js',
    arrow: false,
    description: 'Maps Tailwind utility classes (e.g. `bg-btn-bg`) to CSS variables — so theme/accent changes happen with zero code changes.',
  },
]

// ─── Theme reference data ─────────────────────────────────────────────────────

const themes = [
  { name: 'light', bg: '#ffffff' },
  { name: 'dark', bg: '#032524' },
  { name: 'light-pink', bg: '#FFF3F9' },
  { name: 'pink-mist', bg: '#FFF3F9' },
  { name: 'pink-vivid', bg: '#ffdeef' },
]

const accents = [
  { name: 'default', color: '#fd6c9f', label: 'Pink' },
  { name: 'violet', color: '#9e8cf8', label: 'Violet' },
  { name: 'yellow', color: '#ffd800', label: 'Yellow' },
  { name: 'fuschia', color: '#e6007a', label: 'Fuschia' },
]

// ─── Story ────────────────────────────────────────────────────────────────────

export const Overview: Story = {
  render: () => (
    <div style={{ background: 'var(--bg)', minHeight: '100vh' }}>
      {/* Hero banner */}
      <div
        className="px-8 py-16 border-b border-border"
        style={{ background: 'color-mix(in srgb, var(--accent-btn-bg) 6%, var(--bg))' }}
      >
        <div className="max-w-4xl">
          <span
            className="text-label uppercase tracking-[0.08em] font-semibold inline-block mb-4"
            style={{ color: 'var(--accent-btn-bg)' }}
          >
            Design System
          </span>
          <h1 className="text-h1 font-black text-text mb-4">
            Murfy Design System
          </h1>
          <p className="text-text-large text-text mb-2" style={{ opacity: 0.75 }}>
            Single source of truth for the murfy.fr brand refresh.
          </p>
          <p className="text-text-main text-text" style={{ opacity: 0.55 }}>
            5 themes × 4 accent colors — built in Storybook + React + Tailwind.
            Switch the <strong>Theme</strong> and <strong>Accent</strong> dropdowns in the toolbar
            to preview every combination live, across all components.
          </p>
        </div>
      </div>

      <div className="px-8 py-10 max-w-5xl space-y-0">

        {/* Section: Verticals */}
        <DocSection
          label="The three verticals"
          subtitle="Each activity uses its own accent color. The same component adapts automatically via data-accent — no code changes required."
        >
          <div className="grid grid-cols-1 md:grid-cols-4 gap-4">
            {verticals.map((v) => (
              <div
                key={v.accent}
                className="rounded-[var(--radius-card)] border border-border p-5 flex flex-col gap-3"
                style={{ background: 'var(--bg)' }}
              >
                <div className="flex items-center gap-3">
                  {/* Accent swatch scoped to the right data-accent */}
                  <div data-accent={v.accent} className="flex-shrink-0">
                    <div
                      className="w-8 h-8 rounded-full border border-border"
                      style={{ background: 'var(--accent-btn-bg)' }}
                    />
                  </div>
                  <span className="text-h5 font-bold text-text">{v.emoji} {v.name}</span>
                </div>
                <span
                  className="text-label uppercase tracking-[0.08em] font-semibold"
                  style={{ color: 'var(--accent-btn-bg)' }}
                  data-accent={v.accent}
                >
                  {v.label}
                </span>
                <p className="text-text-xsmall text-text" style={{ opacity: 0.6 }}>
                  {v.description}
                </p>
              </div>
            ))}
          </div>
        </DocSection>

        {/* Section: How the toolbar works */}
        <DocSection
          label="How the toolbar works"
          subtitle="Two dropdowns in the Storybook toolbar control every CSS variable simultaneously."
        >
          <div className="grid grid-cols-1 md:grid-cols-2 gap-6">
            {/* Theme selector */}
            <div
              className="rounded-[var(--radius-card)] border border-border p-6"
              style={{ background: 'var(--bg)' }}
            >
              <p className="text-text-main-semibold font-semibold text-text mb-4">
                Theme selector — 5 options
              </p>
              <p className="text-text-xsmall text-text mb-4" style={{ opacity: 0.6 }}>
                Affects <code className="font-mono">--bg</code>, <code className="font-mono">--text</code>,{' '}
                <code className="font-mono">--btn-bg</code>, and all other semantic tokens.
              </p>
              <div className="flex flex-col gap-2">
                {themes.map((t) => (
                  <div key={t.name} className="flex items-center gap-3">
                    <div
                      className="w-5 h-5 rounded-[var(--radius-small)] border border-border flex-shrink-0"
                      style={{ background: t.bg }}
                    />
                    <code className="text-text-xsmall font-mono text-text">{t.name}</code>
                  </div>
                ))}
              </div>
            </div>

            {/* Accent selector */}
            <div
              className="rounded-[var(--radius-card)] border border-border p-6"
              style={{ background: 'var(--bg)' }}
            >
              <p className="text-text-main-semibold font-semibold text-text mb-4">
                Accent selector — 4 options
              </p>
              <p className="text-text-xsmall text-text mb-4" style={{ opacity: 0.6 }}>
                Affects all <code className="font-mono">--accent-*</code> vars: button colors,
                highlights, pill active states, and more.
              </p>
              <div className="flex flex-col gap-2">
                {accents.map((a) => (
                  <div key={a.name} className="flex items-center gap-3">
                    <div
                      className="w-5 h-5 rounded-full border border-border flex-shrink-0"
                      style={{ background: a.color }}
                    />
                    <code className="text-text-xsmall font-mono text-text">{a.name}</code>
                    <span className="text-text-xsmall text-text" style={{ opacity: 0.5 }}>— {a.label}</span>
                  </div>
                ))}
              </div>
            </div>
          </div>
        </DocSection>

        {/* Section: Component inventory */}
        <DocSection
          label="Component inventory"
          subtitle="Five atomic design layers — from raw tokens to full page scaffolds."
        >
          <div className="grid grid-cols-1 md:grid-cols-5 gap-4">
            {layers.map((layer) => (
              <div
                key={layer.name}
                className="rounded-[var(--radius-card)] border border-border p-5 flex flex-col gap-2"
                style={{ background: 'color-mix(in srgb, var(--accent-btn-bg) 4%, var(--bg))' }}
              >
                <div className="text-h4 mb-1">{layer.emoji}</div>
                <p className="text-text-small-semibold font-semibold text-text">{layer.name}</p>
                <span
                  className="text-label uppercase tracking-[0.08em] font-semibold"
                  style={{ color: 'var(--accent-btn-bg)' }}
                >
                  {layer.count} {layer.count === 1 ? 'story' : 'stories'}
                </span>
                <p className="text-text-xsmall text-text" style={{ opacity: 0.6 }}>
                  {layer.description}
                </p>
              </div>
            ))}
          </div>
        </DocSection>

        {/* Section: Token pipeline */}
        <DocSection
          label="Token pipeline"
          subtitle="tokens.json is the only file you edit. Everything downstream is auto-generated."
        >
          <div className="flex flex-col md:flex-row items-start gap-0 md:gap-0">
            {pipelineSteps.map((step, i) => (
              <React.Fragment key={step.file}>
                <div
                  className="flex-1 rounded-[var(--radius-card)] border border-border p-5"
                  style={{ background: 'var(--bg)' }}
                >
                  <code
                    className="text-text-small-semibold font-semibold font-mono block mb-2"
                    style={{ color: 'var(--accent-btn-bg)' }}
                  >
                    {step.file}
                  </code>
                  <p className="text-text-xsmall text-text" style={{ opacity: 0.65 }}>
                    {step.description}
                  </p>
                </div>
                {step.arrow && (
                  <div
                    className="flex items-center justify-center px-3 py-6 text-h4 flex-shrink-0 self-center"
                    style={{ color: 'var(--accent-btn-bg)', opacity: 0.5 }}
                  >
                    →
                  </div>
                )}
              </React.Fragment>
            ))}
          </div>
        </DocSection>

        {/* Section: Quick links */}
        <DocSection
          label="Quick links"
          subtitle="Jump to key Foundation documentation."
        >
          <div className="flex flex-wrap gap-3">
            <Button variant="secondary" size="sm">Colors</Button>
            <Button variant="secondary" size="sm">Typography</Button>
            <Button variant="secondary" size="sm">Spacing &amp; Radius</Button>
            <Button variant="secondary" size="sm">Theme × Accent Matrix</Button>
            <Button variant="secondary" size="sm">Icons</Button>
            <Button variant="secondary" size="sm">Naming Conventions</Button>
          </div>
        </DocSection>

      </div>
    </div>
  ),
}
